import { createContext, useContext, useState, useEffect } from "react";
import PropTypes from "prop-types";

const LanguageContext = createContext();

const translations = {
  en: {
    // Nav
    nav_home: "Home",
    nav_lighthouse: "Lighthouse",
    nav_services: "Services",
    nav_contact: "Contact",
    // Home / WebsiteGrader
    title: "Website Grader",
    subtitle: "Grade your website in seconds. Then learn how to improve it for free.",
    urlPlaceholder: "https://example.com",
    emailPlaceholder: "Enter Your Email",
    privacyText: "We are committed to your privacy. Mycto uses the information you provide to contact you about relevant content, products, and services. You may unsubscribe at any time. For more information, check out our",
    privacyPolicy: "Privacy Policy",
    getScore: "Get your score",
    analyzing: "Analyzing...",
    featuresTitle: "Get Your Website Rating in Seconds",
    featuresSubtitle: "Website grader tools make understanding website performance easy. Learn about your page performance, security, SEO, and mobile experience.",
    performance: "Performance",
    performanceDesc: "Analyze your website's speed and performance metrics",
    security: "Security",
    securityDesc: "Check your website's security and best practices",
    seo: "SEO",
    seoDesc: "Evaluate your search engine optimization",
    mobile: "Mobile",
    mobileDesc: "Test your website's mobile responsiveness",
    realTimeAnalysis: "Real-time Analysis",
    contactMe: "Contact Me",
    // Lighthouse
    analysisResults: "Analysis Results",
    overallScore: "Overall Score",
    noDataFound: "No Analysis Data Found",
    backToHome: "Back to Home",
    back: "Back",
    // Services
    servicesTitle: "Our Services",
    servicesSubtitle: "Comprehensive web solutions to elevate your online presence and drive business growth.",
    webDev: "Web Development",
    webDevDesc: "Custom website design and development tailored to your business needs.",
    perfOpt: "Performance Optimization",
    perfOptDesc: "Improve website speed, user experience, and search engine rankings.",
    secAudit: "Security Audit",
    secAuditDesc: "Comprehensive security analysis and protection strategies.",
    seoServices: "SEO Services",
    seoServicesDesc: "Enhance your online visibility and attract more organic traffic.",
    responsive: "Responsive Design",
    responsiveDesc: "Ensure your website looks great on all devices and screen sizes.",
    accessibility: "Global Accessibility",
    accessibilityDesc: "Make your website accessible and inclusive for all users.",
    readyTransform: "Ready to Transform Your Web Presence?",
    scheduleConsult: "Schedule a Consultation",
    // Contact
    contactUs: "Contact Us",
    contactSubhead: "We'd love to hear from you!",
    contactDesc: "Have questions about our Website Grader? Want to improve your website's performance, SEO, or best practices? Reach out to us!",
    nameLabel: "Name",
    namePlaceholder: "Your name",
    emailLabel: "Email",
    mobileLabel: "Mobile Number",
    mobilePlaceholder: "1234567890",
    messageLabel: "Message",
    messagePlaceholder: "Type your message here.",
    sendMessage: "Send Message",
    sending: "Sending...",
    messageSent: "Message Sent!",
    messageSentDesc: "Thank you for your message. We'll get back to you soon!",
    messageError: "Error Sending Message",
    messageErrorDesc: "Something went wrong. Please try again later.",
    // Footer
    footerDesc: "Analyze and improve your website's performance with our comprehensive tools.",
    quickLinks: "Quick Links",
    footerContact: "Contact",
    footerContactDesc: "Have questions? Reach out to us for support and inquiries.",
    contactUsBtn: "Contact Us",
    allRights: "All rights reserved.",
    // Errors
    errorUrl: "Please enter a URL",
    errorEmail: "Please enter a valid email address",
    errorInvalidUrl: "Please enter a valid and complete URL (e.g., https://example.com)",
    errorBadRequest: "Invalid URL or request. Please check your website address and try again.",
    errorTooMany: "You have made too many requests. Please wait a minute and try again.",
  },
  de: {
    nav_home: "Startseite", nav_lighthouse: "Lighthouse", nav_services: "Dienste", nav_contact: "Kontakt",
    title: "Website Grader", subtitle: "Bewerten Sie Ihre Website in Sekunden. Lernen Sie dann kostenlos, wie Sie sie verbessern können.",
    urlPlaceholder: "https://beispiel.de", emailPlaceholder: "E-Mail eingeben",
    privacyText: "Wir verpflichten uns zu Ihrer Privatsphäre. Mycto verwendet die von Ihnen bereitgestellten Informationen, um Sie über relevante Inhalte zu informieren. Sie können jederzeit abbestellen. Weitere Informationen in unserer",
    privacyPolicy: "Datenschutzerklärung", getScore: "Bewertung erhalten", analyzing: "Analysiere...",
    featuresTitle: "Erhalten Sie Ihre Website-Bewertung in Sekunden",
    featuresSubtitle: "Website-Grader-Tools machen es einfach, die Website-Performance zu verstehen.",
    performance: "Leistung", performanceDesc: "Analysieren Sie die Geschwindigkeit und Leistungsmetriken Ihrer Website",
    security: "Sicherheit", securityDesc: "Überprüfen Sie die Sicherheit und Best Practices Ihrer Website",
    seo: "SEO", seoDesc: "Bewerten Sie Ihre Suchmaschinenoptimierung",
    mobile: "Mobil", mobileDesc: "Testen Sie die mobile Reaktionsfähigkeit Ihrer Website",
    realTimeAnalysis: "Echtzeit-Analyse", contactMe: "Kontaktiere mich",
    analysisResults: "Analyseergebnisse", overallScore: "Gesamtbewertung",
    noDataFound: "Keine Analysedaten gefunden", backToHome: "Zurück zur Startseite", back: "Zurück",
    servicesTitle: "Unsere Dienste", servicesSubtitle: "Umfassende Weblösungen zur Steigerung Ihrer Online-Präsenz.",
    webDev: "Webentwicklung", webDevDesc: "Maßgeschneidertes Webdesign und Entwicklung.",
    perfOpt: "Leistungsoptimierung", perfOptDesc: "Verbessern Sie Website-Geschwindigkeit und Benutzererfahrung.",
    secAudit: "Sicherheitsaudit", secAuditDesc: "Umfassende Sicherheitsanalyse und Schutzstrategien.",
    seoServices: "SEO-Dienste", seoServicesDesc: "Verbessern Sie Ihre Online-Sichtbarkeit.",
    responsive: "Responsives Design", responsiveDesc: "Stellen Sie sicher, dass Ihre Website auf allen Geräten gut aussieht.",
    accessibility: "Globale Barrierefreiheit", accessibilityDesc: "Machen Sie Ihre Website für alle Benutzer zugänglich.",
    readyTransform: "Bereit, Ihre Web-Präsenz zu transformieren?", scheduleConsult: "Beratung vereinbaren",
    contactUs: "Kontaktieren Sie uns", contactSubhead: "Wir freuen uns von Ihnen zu hören!",
    contactDesc: "Haben Sie Fragen zu unserem Website Grader? Kontaktieren Sie uns!",
    nameLabel: "Name", namePlaceholder: "Ihr Name", emailLabel: "E-Mail",
    mobileLabel: "Handynummer", mobilePlaceholder: "1234567890",
    messageLabel: "Nachricht", messagePlaceholder: "Geben Sie Ihre Nachricht ein.",
    sendMessage: "Nachricht senden", sending: "Wird gesendet...",
    messageSent: "Nachricht gesendet!", messageSentDesc: "Danke für Ihre Nachricht. Wir melden uns bald!",
    messageError: "Fehler beim Senden", messageErrorDesc: "Etwas ist schiefgelaufen. Bitte versuchen Sie es später erneut.",
    footerDesc: "Analysieren und verbessern Sie die Leistung Ihrer Website.", quickLinks: "Schnelllinks",
    footerContact: "Kontakt", footerContactDesc: "Haben Sie Fragen? Kontaktieren Sie uns.",
    contactUsBtn: "Kontaktieren Sie uns", allRights: "Alle Rechte vorbehalten.",
    errorUrl: "Bitte geben Sie eine URL ein", errorEmail: "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    errorInvalidUrl: "Bitte geben Sie eine gültige URL ein", errorBadRequest: "Ungültige URL. Bitte überprüfen Sie Ihre Adresse.",
    errorTooMany: "Zu viele Anfragen. Bitte warten Sie eine Minute.",
  },
  es: {
    nav_home: "Inicio", nav_lighthouse: "Lighthouse", nav_services: "Servicios", nav_contact: "Contacto",
    title: "Website Grader", subtitle: "Califique su sitio web en segundos. Luego aprenda cómo mejorarlo gratis.",
    urlPlaceholder: "https://ejemplo.com", emailPlaceholder: "Ingrese su correo",
    privacyText: "Estamos comprometidos con su privacidad. Mycto utiliza la información que nos proporciona para contactarlo sobre contenido relevante. Puede cancelar su suscripción en cualquier momento. Para más información, consulte nuestra",
    privacyPolicy: "Política de Privacidad", getScore: "Obtener puntuación", analyzing: "Analizando...",
    featuresTitle: "Obtenga la calificación de su sitio en segundos",
    featuresSubtitle: "Las herramientas de calificación de sitios web facilitan la comprensión del rendimiento.",
    performance: "Rendimiento", performanceDesc: "Analice la velocidad y las métricas de rendimiento de su sitio",
    security: "Seguridad", securityDesc: "Verifique la seguridad y las mejores prácticas de su sitio",
    seo: "SEO", seoDesc: "Evalúe su optimización para motores de búsqueda",
    mobile: "Móvil", mobileDesc: "Pruebe la capacidad de respuesta móvil de su sitio",
    realTimeAnalysis: "Análisis en tiempo real", contactMe: "Contáctame",
    analysisResults: "Resultados del análisis", overallScore: "Puntuación general",
    noDataFound: "No se encontraron datos de análisis", backToHome: "Volver al inicio", back: "Volver",
    servicesTitle: "Nuestros Servicios", servicesSubtitle: "Soluciones web integrales para elevar su presencia en línea.",
    webDev: "Desarrollo Web", webDevDesc: "Diseño y desarrollo web personalizado.",
    perfOpt: "Optimización de Rendimiento", perfOptDesc: "Mejore la velocidad y la experiencia del usuario.",
    secAudit: "Auditoría de Seguridad", secAuditDesc: "Análisis de seguridad integral y estrategias de protección.",
    seoServices: "Servicios SEO", seoServicesDesc: "Mejore su visibilidad en línea.",
    responsive: "Diseño Responsivo", responsiveDesc: "Asegúrese de que su sitio se vea bien en todos los dispositivos.",
    accessibility: "Accesibilidad Global", accessibilityDesc: "Haga su sitio accesible para todos los usuarios.",
    readyTransform: "¿Listo para transformar su presencia web?", scheduleConsult: "Agendar consulta",
    contactUs: "Contáctenos", contactSubhead: "¡Nos encantaría saber de usted!",
    contactDesc: "¿Tiene preguntas sobre nuestro Website Grader? ¡Contáctenos!",
    nameLabel: "Nombre", namePlaceholder: "Su nombre", emailLabel: "Correo",
    mobileLabel: "Número móvil", mobilePlaceholder: "1234567890",
    messageLabel: "Mensaje", messagePlaceholder: "Escriba su mensaje aquí.",
    sendMessage: "Enviar mensaje", sending: "Enviando...",
    messageSent: "¡Mensaje enviado!", messageSentDesc: "Gracias por su mensaje. ¡Le responderemos pronto!",
    messageError: "Error al enviar", messageErrorDesc: "Algo salió mal. Intente de nuevo más tarde.",
    footerDesc: "Analice y mejore el rendimiento de su sitio web.", quickLinks: "Enlaces rápidos",
    footerContact: "Contacto", footerContactDesc: "¿Tiene preguntas? Contáctenos.",
    contactUsBtn: "Contáctenos", allRights: "Todos los derechos reservados.",
    errorUrl: "Por favor ingrese una URL", errorEmail: "Por favor ingrese un correo válido",
    errorInvalidUrl: "Por favor ingrese una URL válida", errorBadRequest: "URL inválida. Verifique su dirección.",
    errorTooMany: "Demasiadas solicitudes. Espere un minuto.",
  },
  fr: {
    nav_home: "Accueil", nav_lighthouse: "Lighthouse", nav_services: "Services", nav_contact: "Contact",
    title: "Website Grader", subtitle: "Évaluez votre site web en quelques secondes. Apprenez ensuite à l'améliorer gratuitement.",
    urlPlaceholder: "https://exemple.fr", emailPlaceholder: "Entrez votre e-mail",
    privacyText: "Nous nous engageons à protéger votre vie privée. Mycto utilise les informations que vous fournissez pour vous contacter. Vous pouvez vous désabonner à tout moment. Pour plus d'informations, consultez notre",
    privacyPolicy: "Politique de confidentialité", getScore: "Obtenir votre score", analyzing: "Analyse en cours...",
    featuresTitle: "Obtenez la note de votre site en quelques secondes",
    featuresSubtitle: "Les outils d'évaluation de sites web facilitent la compréhension des performances.",
    performance: "Performance", performanceDesc: "Analysez la vitesse et les métriques de performance de votre site",
    security: "Sécurité", securityDesc: "Vérifiez la sécurité et les bonnes pratiques de votre site",
    seo: "SEO", seoDesc: "Évaluez votre optimisation pour les moteurs de recherche",
    mobile: "Mobile", mobileDesc: "Testez la réactivité mobile de votre site",
    realTimeAnalysis: "Analyse en temps réel", contactMe: "Contactez-moi",
    analysisResults: "Résultats de l'analyse", overallScore: "Score global",
    noDataFound: "Aucune donnée d'analyse trouvée", backToHome: "Retour à l'accueil", back: "Retour",
    servicesTitle: "Nos Services", servicesSubtitle: "Solutions web complètes pour élever votre présence en ligne.",
    webDev: "Développement Web", webDevDesc: "Conception et développement web sur mesure.",
    perfOpt: "Optimisation des performances", perfOptDesc: "Améliorez la vitesse et l'expérience utilisateur.",
    secAudit: "Audit de sécurité", secAuditDesc: "Analyse de sécurité complète et stratégies de protection.",
    seoServices: "Services SEO", seoServicesDesc: "Améliorez votre visibilité en ligne.",
    responsive: "Design Responsive", responsiveDesc: "Assurez-vous que votre site est beau sur tous les appareils.",
    accessibility: "Accessibilité Globale", accessibilityDesc: "Rendez votre site accessible à tous les utilisateurs.",
    readyTransform: "Prêt à transformer votre présence web?", scheduleConsult: "Planifier une consultation",
    contactUs: "Contactez-nous", contactSubhead: "Nous serions ravis de vous entendre!",
    contactDesc: "Des questions sur notre Website Grader? Contactez-nous!",
    nameLabel: "Nom", namePlaceholder: "Votre nom", emailLabel: "E-mail",
    mobileLabel: "Numéro de mobile", mobilePlaceholder: "1234567890",
    messageLabel: "Message", messagePlaceholder: "Tapez votre message ici.",
    sendMessage: "Envoyer le message", sending: "Envoi en cours...",
    messageSent: "Message envoyé!", messageSentDesc: "Merci pour votre message. Nous vous répondrons bientôt!",
    messageError: "Erreur d'envoi", messageErrorDesc: "Un problème est survenu. Veuillez réessayer plus tard.",
    footerDesc: "Analysez et améliorez les performances de votre site web.", quickLinks: "Liens rapides",
    footerContact: "Contact", footerContactDesc: "Des questions? Contactez-nous.",
    contactUsBtn: "Contactez-nous", allRights: "Tous droits réservés.",
    errorUrl: "Veuillez entrer une URL", errorEmail: "Veuillez entrer une adresse e-mail valide",
    errorInvalidUrl: "Veuillez entrer une URL valide", errorBadRequest: "URL invalide. Vérifiez votre adresse.",
    errorTooMany: "Trop de requêtes. Veuillez attendre une minute.",
  },
  ja: {
    nav_home: "ホーム", nav_lighthouse: "Lighthouse", nav_services: "サービス", nav_contact: "お問い合わせ",
    title: "Website Grader", subtitle: "数秒でウェブサイトを評価。無料で改善方法を学びましょう。",
    urlPlaceholder: "https://example.com", emailPlaceholder: "メールアドレスを入力",
    privacyText: "私たちはあなたのプライバシーを尊重します。Myctoはあなたの情報を使用して関連するコンテンツについてご連絡します。いつでも配信停止できます。詳しくは",
    privacyPolicy: "プライバシーポリシー", getScore: "スコアを取得", analyzing: "分析中...",
    featuresTitle: "数秒でウェブサイトの評価を取得",
    featuresSubtitle: "ウェブサイト評価ツールでパフォーマンスを簡単に理解できます。",
    performance: "パフォーマンス", performanceDesc: "ウェブサイトの速度とパフォーマンス指標を分析",
    security: "セキュリティ", securityDesc: "ウェブサイトのセキュリティとベストプラクティスを確認",
    seo: "SEO", seoDesc: "検索エンジン最適化を評価",
    mobile: "モバイル", mobileDesc: "ウェブサイトのモバイル対応をテスト",
    realTimeAnalysis: "リアルタイム分析", contactMe: "お問い合わせ",
    analysisResults: "分析結果", overallScore: "総合スコア",
    noDataFound: "分析データが見つかりません", backToHome: "ホームに戻る", back: "戻る",
    servicesTitle: "サービス一覧", servicesSubtitle: "オンラインプレゼンスを高める包括的なウェブソリューション。",
    webDev: "ウェブ開発", webDevDesc: "ビジネスニーズに合わせたカスタムウェブデザインと開発。",
    perfOpt: "パフォーマンス最適化", perfOptDesc: "ウェブサイトの速度とユーザー体験を向上。",
    secAudit: "セキュリティ監査", secAuditDesc: "包括的なセキュリティ分析と保護戦略。",
    seoServices: "SEOサービス", seoServicesDesc: "オンラインの可視性を向上。",
    responsive: "レスポンシブデザイン", responsiveDesc: "すべてのデバイスで美しく表示。",
    accessibility: "グローバルアクセシビリティ", accessibilityDesc: "すべてのユーザーにアクセス可能なウェブサイト。",
    readyTransform: "ウェブプレゼンスを変革する準備はできましたか？", scheduleConsult: "相談を予約",
    contactUs: "お問い合わせ", contactSubhead: "ご連絡をお待ちしております！",
    contactDesc: "Website Graderについてご質問がありますか？お気軽にお問い合わせください！",
    nameLabel: "名前", namePlaceholder: "お名前", emailLabel: "メール",
    mobileLabel: "電話番号", mobilePlaceholder: "1234567890",
    messageLabel: "メッセージ", messagePlaceholder: "メッセージを入力してください。",
    sendMessage: "メッセージを送信", sending: "送信中...",
    messageSent: "送信完了！", messageSentDesc: "メッセージありがとうございます。すぐにご返信いたします！",
    messageError: "送信エラー", messageErrorDesc: "問題が発生しました。後でもう一度お試しください。",
    footerDesc: "包括的なツールでウェブサイトのパフォーマンスを分析・改善。", quickLinks: "クイックリンク",
    footerContact: "連絡先", footerContactDesc: "ご質問がありますか？お気軽にお問い合わせください。",
    contactUsBtn: "お問い合わせ", allRights: "全著作権所有。",
    errorUrl: "URLを入力してください", errorEmail: "有効なメールアドレスを入力してください",
    errorInvalidUrl: "有効なURLを入力してください", errorBadRequest: "無効なURL。アドレスを確認してください。",
    errorTooMany: "リクエストが多すぎます。しばらくお待ちください。",
  },
  pt: {
    nav_home: "Início", nav_lighthouse: "Lighthouse", nav_services: "Serviços", nav_contact: "Contato",
    title: "Website Grader", subtitle: "Avalie seu site em segundos. Depois aprenda como melhorá-lo gratuitamente.",
    urlPlaceholder: "https://exemplo.com", emailPlaceholder: "Digite seu e-mail",
    privacyText: "Estamos comprometidos com sua privacidade. Mycto usa as informações que você fornece para contatá-lo sobre conteúdo relevante. Você pode cancelar a qualquer momento. Para mais informações, consulte nossa",
    privacyPolicy: "Política de Privacidade", getScore: "Obter pontuação", analyzing: "Analisando...",
    featuresTitle: "Obtenha a avaliação do seu site em segundos",
    featuresSubtitle: "As ferramentas de avaliação facilitam a compreensão do desempenho do site.",
    performance: "Desempenho", performanceDesc: "Analise a velocidade e as métricas de desempenho do seu site",
    security: "Segurança", securityDesc: "Verifique a segurança e as melhores práticas do seu site",
    seo: "SEO", seoDesc: "Avalie sua otimização para mecanismos de busca",
    mobile: "Móvel", mobileDesc: "Teste a responsividade móvel do seu site",
    realTimeAnalysis: "Análise em tempo real", contactMe: "Entre em contato",
    analysisResults: "Resultados da análise", overallScore: "Pontuação geral",
    noDataFound: "Nenhum dado de análise encontrado", backToHome: "Voltar ao início", back: "Voltar",
    servicesTitle: "Nossos Serviços", servicesSubtitle: "Soluções web abrangentes para elevar sua presença online.",
    webDev: "Desenvolvimento Web", webDevDesc: "Design e desenvolvimento web personalizado.",
    perfOpt: "Otimização de Desempenho", perfOptDesc: "Melhore a velocidade e a experiência do usuário.",
    secAudit: "Auditoria de Segurança", secAuditDesc: "Análise de segurança abrangente e estratégias de proteção.",
    seoServices: "Serviços de SEO", seoServicesDesc: "Melhore sua visibilidade online.",
    responsive: "Design Responsivo", responsiveDesc: "Garanta que seu site fique ótimo em todos os dispositivos.",
    accessibility: "Acessibilidade Global", accessibilityDesc: "Torne seu site acessível para todos os usuários.",
    readyTransform: "Pronto para transformar sua presença web?", scheduleConsult: "Agendar consulta",
    contactUs: "Fale Conosco", contactSubhead: "Adoraríamos ouvir de você!",
    contactDesc: "Tem perguntas sobre nosso Website Grader? Entre em contato!",
    nameLabel: "Nome", namePlaceholder: "Seu nome", emailLabel: "E-mail",
    mobileLabel: "Celular", mobilePlaceholder: "1234567890",
    messageLabel: "Mensagem", messagePlaceholder: "Digite sua mensagem aqui.",
    sendMessage: "Enviar mensagem", sending: "Enviando...",
    messageSent: "Mensagem enviada!", messageSentDesc: "Obrigado pela mensagem. Responderemos em breve!",
    messageError: "Erro ao enviar", messageErrorDesc: "Algo deu errado. Tente novamente mais tarde.",
    footerDesc: "Analise e melhore o desempenho do seu site.", quickLinks: "Links rápidos",
    footerContact: "Contato", footerContactDesc: "Tem perguntas? Entre em contato conosco.",
    contactUsBtn: "Fale Conosco", allRights: "Todos os direitos reservados.",
    errorUrl: "Por favor, insira uma URL", errorEmail: "Por favor, insira um e-mail válido",
    errorInvalidUrl: "Por favor, insira uma URL válida", errorBadRequest: "URL inválida. Verifique seu endereço.",
    errorTooMany: "Muitas solicitações. Aguarde um minuto.",
  },
};

const languageNames = {
  en: { name: "English", flag: "🇺🇸" },
  de: { name: "Deutsch", flag: "🇩🇪" },
  es: { name: "Español", flag: "🇪🇸" },
  fr: { name: "Français", flag: "🇫🇷" },
  ja: { name: "日本語", flag: "🇯🇵" },
  pt: { name: "Português", flag: "🇵🇹" },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("preferredLanguage") || "en";
  });

  useEffect(() => {
    localStorage.setItem("preferredLanguage", language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageNames }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};

LanguageProvider.propTypes = {
  children: PropTypes.node.isRequired,
};

export default LanguageContext;
